name: Docker image workflow

on:
  - push
  - workflow_dispatch

jobs:
  image-workflow:
    # test
    uses: kerrys-learning-lab/.github/.github/workflows/docker-image.workflow.yml@initial-development
